[config]
exclude-files = [
    "examples/*",
    "target/*",
    "volga/tests/*",
    "volga/benches/*",
    "volga-macros/src/*",
    
    # This is covered implicitly in integration tests
    "volga/src/server/*",

    # This is test utilities that used in integration tests
    "volga/src/test/*",
    "volga/src/test.rs",
]

ignore-tests = true
ignore-panics = true
