[config]
exclude-files = [
    "examples/*",
    "target/*",
    "volga/tests/*",
    "volga/benches/*",
    "volga-macros/src/*",
    
    # This is covered implicitly in integration tests
    "volga/src/server/*",
    
    # Exclude the trybuild tests
    "volga-macro/tests/*"
]

ignore-tests = true
ignore-panics = true
