blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/RomanEmreis/volga/discussions
    about: Please use Discussions for questions and early ideas.
