[package]
name = "open_api"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
volga = { path = "../../volga", features = ["openapi"] }
serde = { version = "1.0.219", features = ["serde_derive"] }
tokio = "1.49.0"

[lints]
workspace = true