[package]
name = "sse"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = "1.49.0"
serde = { version = "1.0.228", features = ["serde_derive"] }
volga = { path = "../../volga" }

[lints]
workspace = true
