[package]
name = "volga-dev-cert"
version = "0.6.8"
edition = "2024"
rust-version = "1.90.0"
authors = ["Roman Emreis <roman.emreis@outlook.com>"]
license = "MIT"
repository = "https://github.com/RomanEmreis/volga"
description = "A Rust library for generating self-signed TLS certificates for local development."
documentation = "https://docs.rs/volga"
readme = "README.md"
homepage = "https://romanemreis.github.io/volga-docs"
categories = [
    "web-programming::http-server",
    "web-programming::websocket",
    "network-programming",
    "asynchronous",
]
keywords = ["volga", "server", "https", "tls"]

[dependencies]
rcgen = "0.14.5"

[lints]
workspace = true
